// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footerBtn': string;
  'selected': string;
}
declare var cssExports: CssExports;
export = cssExports;
